name: Node.js CI

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - run: npm ci
      - run: npm run build --if-present

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
